[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT --strictPort"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
VITE_API_URL = "https://courtside-backend-production.up.railway.app"
VITE_TELEGRAM_BOT_TOKEN = "7577073157:AAHtnMehnBElFKxwSNHLPJV6ehG2VSfSsrw"
VITE_APP_VERSION = "2.0.0"
TZ = "Asia/Phnom_Penh"